// Code generated by protoc-gen-go. DO NOT EDIT.
// source: review/review.proto

package review

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ReviewQuery
type ReviewQuery struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Review               *ReviewSchema `protobuf:"bytes,2,opt,name=review,proto3" json:"review,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReviewQuery) Reset()         { *m = ReviewQuery{} }
func (m *ReviewQuery) String() string { return proto.CompactTextString(m) }
func (*ReviewQuery) ProtoMessage()    {}
func (*ReviewQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_24db6fb4010ad353, []int{0}
}
func (m *ReviewQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewQuery.Unmarshal(m, b)
}
func (m *ReviewQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewQuery.Marshal(b, m, deterministic)
}
func (dst *ReviewQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewQuery.Merge(dst, src)
}
func (m *ReviewQuery) XXX_Size() int {
	return xxx_messageInfo_ReviewQuery.Size(m)
}
func (m *ReviewQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewQuery proto.InternalMessageInfo

func (m *ReviewQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReviewQuery) GetReview() *ReviewSchema {
	if m != nil {
		return m.Review
	}
	return nil
}

// The review interface schema
type ReviewSchema struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Rating               int32    `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Review               string   `protobuf:"bytes,3,opt,name=review,proto3" json:"review,omitempty"`
	CustomerId           int32    `protobuf:"varint,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ProductId            int32    `protobuf:"varint,5,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewSchema) Reset()         { *m = ReviewSchema{} }
func (m *ReviewSchema) String() string { return proto.CompactTextString(m) }
func (*ReviewSchema) ProtoMessage()    {}
func (*ReviewSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_24db6fb4010ad353, []int{1}
}
func (m *ReviewSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewSchema.Unmarshal(m, b)
}
func (m *ReviewSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewSchema.Marshal(b, m, deterministic)
}
func (dst *ReviewSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewSchema.Merge(dst, src)
}
func (m *ReviewSchema) XXX_Size() int {
	return xxx_messageInfo_ReviewSchema.Size(m)
}
func (m *ReviewSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewSchema.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewSchema proto.InternalMessageInfo

func (m *ReviewSchema) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ReviewSchema) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *ReviewSchema) GetReview() string {
	if m != nil {
		return m.Review
	}
	return ""
}

func (m *ReviewSchema) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *ReviewSchema) GetProductId() int32 {
	if m != nil {
		return m.ProductId
	}
	return 0
}

// ReviewsQuery describes a Query to get count reviews starting at id start
type ReviewsQuery struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Start                int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewsQuery) Reset()         { *m = ReviewsQuery{} }
func (m *ReviewsQuery) String() string { return proto.CompactTextString(m) }
func (*ReviewsQuery) ProtoMessage()    {}
func (*ReviewsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_24db6fb4010ad353, []int{2}
}
func (m *ReviewsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewsQuery.Unmarshal(m, b)
}
func (m *ReviewsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewsQuery.Marshal(b, m, deterministic)
}
func (dst *ReviewsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewsQuery.Merge(dst, src)
}
func (m *ReviewsQuery) XXX_Size() int {
	return xxx_messageInfo_ReviewsQuery.Size(m)
}
func (m *ReviewsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewsQuery proto.InternalMessageInfo

func (m *ReviewsQuery) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ReviewsQuery) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

// ReviewsResponse is a list of reviews
type ReviewsResponse struct {
	Reviews              []*ReviewSchema `protobuf:"bytes,1,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReviewsResponse) Reset()         { *m = ReviewsResponse{} }
func (m *ReviewsResponse) String() string { return proto.CompactTextString(m) }
func (*ReviewsResponse) ProtoMessage()    {}
func (*ReviewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_review_24db6fb4010ad353, []int{3}
}
func (m *ReviewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewsResponse.Unmarshal(m, b)
}
func (m *ReviewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewsResponse.Marshal(b, m, deterministic)
}
func (dst *ReviewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewsResponse.Merge(dst, src)
}
func (m *ReviewsResponse) XXX_Size() int {
	return xxx_messageInfo_ReviewsResponse.Size(m)
}
func (m *ReviewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewsResponse proto.InternalMessageInfo

func (m *ReviewsResponse) GetReviews() []*ReviewSchema {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func init() {
	proto.RegisterType((*ReviewQuery)(nil), "review.ReviewQuery")
	proto.RegisterType((*ReviewSchema)(nil), "review.ReviewSchema")
	proto.RegisterType((*ReviewsQuery)(nil), "review.ReviewsQuery")
	proto.RegisterType((*ReviewsResponse)(nil), "review.ReviewsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReviewServiceClient is the client API for ReviewService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReviewServiceClient interface {
	// Create a review
	CreateReview(ctx context.Context, in *ReviewSchema, opts ...grpc.CallOption) (*ReviewSchema, error)
	// Get a review by id
	GetReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*ReviewSchema, error)
	// Update a review by id
	UpdateReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*ReviewSchema, error)
	// Delete a review by id
	DeleteReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	// GetReviews gets a list of reviews by start and count
	GetReviews(ctx context.Context, in *ReviewsQuery, opts ...grpc.CallOption) (*ReviewsResponse, error)
}

type reviewServiceClient struct {
	cc *grpc.ClientConn
}

func NewReviewServiceClient(cc *grpc.ClientConn) ReviewServiceClient {
	return &reviewServiceClient{cc}
}

func (c *reviewServiceClient) CreateReview(ctx context.Context, in *ReviewSchema, opts ...grpc.CallOption) (*ReviewSchema, error) {
	out := new(ReviewSchema)
	err := c.cc.Invoke(ctx, "/review.ReviewService/CreateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) GetReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*ReviewSchema, error) {
	out := new(ReviewSchema)
	err := c.cc.Invoke(ctx, "/review.ReviewService/GetReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) UpdateReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*ReviewSchema, error) {
	out := new(ReviewSchema)
	err := c.cc.Invoke(ctx, "/review.ReviewService/UpdateReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) DeleteReview(ctx context.Context, in *ReviewQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/review.ReviewService/DeleteReview", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewServiceClient) GetReviews(ctx context.Context, in *ReviewsQuery, opts ...grpc.CallOption) (*ReviewsResponse, error) {
	out := new(ReviewsResponse)
	err := c.cc.Invoke(ctx, "/review.ReviewService/GetReviews", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewServiceServer is the server API for ReviewService service.
type ReviewServiceServer interface {
	// Create a review
	CreateReview(context.Context, *ReviewSchema) (*ReviewSchema, error)
	// Get a review by id
	GetReview(context.Context, *ReviewQuery) (*ReviewSchema, error)
	// Update a review by id
	UpdateReview(context.Context, *ReviewQuery) (*ReviewSchema, error)
	// Delete a review by id
	DeleteReview(context.Context, *ReviewQuery) (*wrappers.StringValue, error)
	// GetReviews gets a list of reviews by start and count
	GetReviews(context.Context, *ReviewsQuery) (*ReviewsResponse, error)
}

func RegisterReviewServiceServer(s *grpc.Server, srv ReviewServiceServer) {
	s.RegisterService(&_ReviewService_serviceDesc, srv)
}

func _ReviewService_CreateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).CreateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/CreateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).CreateReview(ctx, req.(*ReviewSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_GetReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/GetReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetReview(ctx, req.(*ReviewQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_UpdateReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).UpdateReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/UpdateReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).UpdateReview(ctx, req.(*ReviewQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_DeleteReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).DeleteReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/DeleteReview",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).DeleteReview(ctx, req.(*ReviewQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReviewService_GetReviews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServiceServer).GetReviews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.ReviewService/GetReviews",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServiceServer).GetReviews(ctx, req.(*ReviewsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReviewService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "review.ReviewService",
	HandlerType: (*ReviewServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReview",
			Handler:    _ReviewService_CreateReview_Handler,
		},
		{
			MethodName: "GetReview",
			Handler:    _ReviewService_GetReview_Handler,
		},
		{
			MethodName: "UpdateReview",
			Handler:    _ReviewService_UpdateReview_Handler,
		},
		{
			MethodName: "DeleteReview",
			Handler:    _ReviewService_DeleteReview_Handler,
		},
		{
			MethodName: "GetReviews",
			Handler:    _ReviewService_GetReviews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review/review.proto",
}

func init() { proto.RegisterFile("review/review.proto", fileDescriptor_review_24db6fb4010ad353) }

var fileDescriptor_review_24db6fb4010ad353 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0xd2, 0x2f, 0xfd, 0xe8, 0x6d, 0x54, 0x98, 0x16, 0x0d, 0xc5, 0x9f, 0x90, 0x55, 0x17,
	0x92, 0x42, 0xdd, 0x88, 0x3f, 0x0b, 0xa9, 0x20, 0xc5, 0x95, 0x29, 0xba, 0x95, 0x34, 0xb9, 0xc6,
	0x81, 0x36, 0x13, 0x66, 0x26, 0x2d, 0xbe, 0x84, 0xcf, 0xe5, 0x63, 0x49, 0x67, 0x26, 0xfe, 0xd4,
	0x56, 0x70, 0x15, 0xee, 0xb9, 0xe7, 0x9c, 0x7b, 0xee, 0xe4, 0x42, 0x9b, 0xe3, 0x9c, 0xe2, 0xa2,
	0xaf, 0x3f, 0x61, 0xc1, 0x99, 0x64, 0xa4, 0xa1, 0xab, 0xee, 0x61, 0xc6, 0x58, 0x36, 0xc5, 0xbe,
	0x42, 0x27, 0xe5, 0x53, 0x7f, 0xc1, 0xe3, 0xa2, 0x40, 0x2e, 0x34, 0x2f, 0xb8, 0x85, 0x56, 0xa4,
	0x98, 0x77, 0x25, 0xf2, 0x17, 0xb2, 0x0d, 0x36, 0x4d, 0x3d, 0xcb, 0xb7, 0x7a, 0x4e, 0x64, 0xd3,
	0x94, 0x1c, 0x83, 0x31, 0xf2, 0x6c, 0xdf, 0xea, 0xb5, 0x06, 0x9d, 0xd0, 0x4c, 0xd1, 0xa2, 0x71,
	0xf2, 0x8c, 0xb3, 0x38, 0x32, 0x9c, 0xe0, 0xd5, 0x02, 0xf7, 0x6b, 0xe3, 0x87, 0xdd, 0x2e, 0x34,
	0x78, 0x2c, 0x69, 0x9e, 0x29, 0x3b, 0x27, 0x32, 0x95, 0xc2, 0xf5, 0x98, 0xba, 0x6f, 0xf5, 0x9a,
	0x95, 0x21, 0x39, 0x82, 0x56, 0x52, 0x0a, 0xc9, 0x66, 0xc8, 0x1f, 0x69, 0xea, 0xfd, 0x53, 0x22,
	0xa8, 0xa0, 0x51, 0x4a, 0x0e, 0x00, 0x0a, 0xce, 0xd2, 0x32, 0x91, 0xcb, 0xbe, 0xa3, 0xfa, 0x4d,
	0x83, 0x8c, 0xd2, 0xe0, 0xac, 0xca, 0x23, 0xf4, 0x7a, 0x1d, 0x70, 0x12, 0x56, 0xe6, 0xd2, 0x44,
	0xd2, 0xc5, 0x12, 0x15, 0x32, 0xe6, 0xd2, 0x84, 0xd2, 0x45, 0x70, 0x05, 0x3b, 0x46, 0x1b, 0xa1,
	0x28, 0x58, 0x2e, 0x90, 0x84, 0xf0, 0x5f, 0x07, 0x13, 0x9e, 0xe5, 0xd7, 0x37, 0x3e, 0x47, 0x45,
	0x1a, 0xbc, 0xd9, 0xb0, 0x65, 0x3a, 0xc8, 0xe7, 0x34, 0x41, 0x72, 0x01, 0xee, 0x90, 0x63, 0x2c,
	0x51, 0xc3, 0x64, 0xad, 0x41, 0x77, 0x2d, 0x1a, 0xd4, 0xc8, 0x29, 0x34, 0x6f, 0x50, 0x1a, 0x69,
	0xfb, 0x3b, 0x49, 0x2d, 0xb8, 0x51, 0x79, 0x0e, 0xee, 0x7d, 0x91, 0x7e, 0xce, 0xfd, 0x93, 0x78,
	0x08, 0xee, 0x35, 0x4e, 0xf1, 0x77, 0xf1, 0x7e, 0xa8, 0x2f, 0x2d, 0xac, 0x2e, 0x2d, 0x1c, 0x4b,
	0x4e, 0xf3, 0xec, 0x21, 0x9e, 0x96, 0x18, 0xd4, 0xc8, 0x25, 0xc0, 0x47, 0x76, 0xb1, 0xba, 0xb7,
	0xfe, 0x3d, 0xdd, 0xbd, 0x15, 0xb4, 0x7a, 0xf8, 0xa0, 0x36, 0x69, 0x28, 0xdb, 0x93, 0xf7, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xce, 0x51, 0x5c, 0x95, 0xed, 0x02, 0x00, 0x00,
}
