version: '2'
services:
  localdev:
    build:
      context: .
      dockerfile: ./Dockerfile.localdev
    command: go run main.go
    environment:
      - APP_DB_USERNAME=dev
      - APP_DB_PASSWORD=dev
      - APP_DB_NAME=dev
      - PORT=8080
    links:
      - postgres
    volumes:
      - ./app/:/go/src/app
      - "vendor:/go/src/app/vendor"
      - "_tools:/go/src/app/_tools"
      - /go/src/app/build
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      dockerfile: ./Dockerfile.localdev
    command: sh -c "retool do golint `go list ./... | grep -v /vendor/` && retool do go test ./... -v"
    environment:
      - APP_DB_USERNAME=dev
      - APP_DB_PASSWORD=dev
      - APP_DB_NAME=test
      - PORT=8080
    links:
      - postgres
    volumes:
      - ./app/:/go/src/app
      - "vendor:/go/src/app/vendor"
      - "_tools:/go/src/app/_tools"
      - /go/src/app/build

  manage_db:
    build:
      context: .
      dockerfile: ./Dockerfile.manage_db
    command: upgrade
    entrypoint: python3 manage.py db
    environment:
      - REALM=localdev
      - PYTHONUNBUFFERED=true
    links:
      - postgres
    volumes:
      - ./db:/code

  lint:
    build:
      context: .
      dockerfile: ./Dockerfile.manage_db
    entrypoint: flake8
    volumes:
      - ./db/:/code
    environment:
      - REALM=test
      - PYTHONUNBUFFERED=true

  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    volumes:
      - "postgres:/var/lib/postgresql/data"

  protoc:
    build:
      context: .
      dockerfile: ./Dockerfile.protoc
    entrypoint: protoc --go_out=plugins=grpc:.
    volumes:
      - ./app/:/go/src/app
      - /go/src/app/build

volumes:
  postgres:
  vendor:
  _tools:
