"""Add Customer, Review and Merchant tables

Revision ID: 2946eee19802
Revises: 0e394ab31a97
Create Date: 2018-06-14 03:10:18.879271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2946eee19802'
down_revision = '0e394ab31a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.UnicodeText(), nullable=False),
    sa.Column('last_name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_table('merchant',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant'))
    )
    op.create_table('review',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.UnicodeText(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_review_customer_id_customer')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_review_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.add_column('product', sa.Column('merchant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_product_merchant_id_merchant'), 'product', 'merchant', ['merchant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_merchant_id_merchant'), 'product', type_='foreignkey')
    op.drop_column('product', 'merchant_id')
    op.drop_table('review')
    op.drop_table('merchant')
    op.drop_table('customer')
    # ### end Alembic commands ###
