"""Initial Schema

Revision ID: 8a5b09852d9c
Revises: 
Create Date: 2018-10-31 02:36:42.809215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5b09852d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.UnicodeText(), nullable=False),
    sa.Column('last_name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_index('ix_customer_deleted_at', 'customer', ['deleted_at'], unique=False)
    op.create_table('merchant',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant'))
    )
    op.create_index('ix_merchant_deleted_at', 'merchant', ['deleted_at'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.Column('price', sa.Numeric(precision=30, scale=16), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.id'], name=op.f('fk_product_merchant_id_merchant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index('ix_product_deleted_at', 'product', ['deleted_at'], unique=False)
    op.create_table('review',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.UnicodeText(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_review_customer_id_customer')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_review_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.create_index('ix_review_deleted_at', 'review', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_deleted_at', table_name='review')
    op.drop_table('review')
    op.drop_index('ix_product_deleted_at', table_name='product')
    op.drop_table('product')
    op.drop_index('ix_merchant_deleted_at', table_name='merchant')
    op.drop_table('merchant')
    op.drop_index('ix_customer_deleted_at', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
