"""Add Customer, Review and Vendor tables

Revision ID: 8ffce1ac5379
Revises: 0e394ab31a97
Create Date: 2018-06-12 05:36:53.267952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ffce1ac5379'
down_revision = '0e394ab31a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.UnicodeText(), nullable=False),
    sa.Column('last_name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer'))
    )
    op.create_table('vendor',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.UnicodeText(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor'))
    )
    op.create_table('review',
    sa.Column('committed_timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.UnicodeText(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('fk_review_customer_id_customer')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_review_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    op.add_column('product', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_product_vendor_id_vendor'), 'product', 'vendor', ['vendor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_product_vendor_id_vendor'), 'product', type_='foreignkey')
    op.drop_column('product', 'vendor_id')
    op.drop_table('review')
    op.drop_table('vendor')
    op.drop_table('customer')
    # ### end Alembic commands ###
