// Code generated by protoc-gen-go. DO NOT EDIT.
// source: merchant/merchant.proto

package merchant

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MerchantQuery
type MerchantQuery struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Merchant             *MerchantSchema `protobuf:"bytes,2,opt,name=merchant,proto3" json:"merchant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MerchantQuery) Reset()         { *m = MerchantQuery{} }
func (m *MerchantQuery) String() string { return proto.CompactTextString(m) }
func (*MerchantQuery) ProtoMessage()    {}
func (*MerchantQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_fdfe9aaf20316dc3, []int{0}
}
func (m *MerchantQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantQuery.Unmarshal(m, b)
}
func (m *MerchantQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantQuery.Marshal(b, m, deterministic)
}
func (dst *MerchantQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantQuery.Merge(dst, src)
}
func (m *MerchantQuery) XXX_Size() int {
	return xxx_messageInfo_MerchantQuery.Size(m)
}
func (m *MerchantQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantQuery proto.InternalMessageInfo

func (m *MerchantQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MerchantQuery) GetMerchant() *MerchantSchema {
	if m != nil {
		return m.Merchant
	}
	return nil
}

// The merchant interface schema
type MerchantSchema struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantSchema) Reset()         { *m = MerchantSchema{} }
func (m *MerchantSchema) String() string { return proto.CompactTextString(m) }
func (*MerchantSchema) ProtoMessage()    {}
func (*MerchantSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_fdfe9aaf20316dc3, []int{1}
}
func (m *MerchantSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantSchema.Unmarshal(m, b)
}
func (m *MerchantSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantSchema.Marshal(b, m, deterministic)
}
func (dst *MerchantSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantSchema.Merge(dst, src)
}
func (m *MerchantSchema) XXX_Size() int {
	return xxx_messageInfo_MerchantSchema.Size(m)
}
func (m *MerchantSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantSchema.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantSchema proto.InternalMessageInfo

func (m *MerchantSchema) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MerchantSchema) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// MerchantsQuery describes a request to get count merchants starting at id start
type MerchantsQuery struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Start                int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MerchantsQuery) Reset()         { *m = MerchantsQuery{} }
func (m *MerchantsQuery) String() string { return proto.CompactTextString(m) }
func (*MerchantsQuery) ProtoMessage()    {}
func (*MerchantsQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_fdfe9aaf20316dc3, []int{2}
}
func (m *MerchantsQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsQuery.Unmarshal(m, b)
}
func (m *MerchantsQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsQuery.Marshal(b, m, deterministic)
}
func (dst *MerchantsQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsQuery.Merge(dst, src)
}
func (m *MerchantsQuery) XXX_Size() int {
	return xxx_messageInfo_MerchantsQuery.Size(m)
}
func (m *MerchantsQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsQuery.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsQuery proto.InternalMessageInfo

func (m *MerchantsQuery) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *MerchantsQuery) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

// MerchantsResponse is a list of merchants
type MerchantsResponse struct {
	Merchants            []*MerchantSchema `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MerchantsResponse) Reset()         { *m = MerchantsResponse{} }
func (m *MerchantsResponse) String() string { return proto.CompactTextString(m) }
func (*MerchantsResponse) ProtoMessage()    {}
func (*MerchantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_merchant_fdfe9aaf20316dc3, []int{3}
}
func (m *MerchantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MerchantsResponse.Unmarshal(m, b)
}
func (m *MerchantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MerchantsResponse.Marshal(b, m, deterministic)
}
func (dst *MerchantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantsResponse.Merge(dst, src)
}
func (m *MerchantsResponse) XXX_Size() int {
	return xxx_messageInfo_MerchantsResponse.Size(m)
}
func (m *MerchantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantsResponse proto.InternalMessageInfo

func (m *MerchantsResponse) GetMerchants() []*MerchantSchema {
	if m != nil {
		return m.Merchants
	}
	return nil
}

func init() {
	proto.RegisterType((*MerchantQuery)(nil), "merchant.MerchantQuery")
	proto.RegisterType((*MerchantSchema)(nil), "merchant.MerchantSchema")
	proto.RegisterType((*MerchantsQuery)(nil), "merchant.MerchantsQuery")
	proto.RegisterType((*MerchantsResponse)(nil), "merchant.MerchantsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MerchantServiceClient is the client API for MerchantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MerchantServiceClient interface {
	// Create a merchant
	CreateMerchant(ctx context.Context, in *MerchantSchema, opts ...grpc.CallOption) (*MerchantSchema, error)
	// Get a merchant by id
	GetMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*MerchantSchema, error)
	// Update a merchant by id
	UpdateMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*MerchantSchema, error)
	// Delete a merchant by id
	DeleteMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	// GetMerchants gets a list of merchants by start and count
	GetMerchants(ctx context.Context, in *MerchantsQuery, opts ...grpc.CallOption) (*MerchantsResponse, error)
}

type merchantServiceClient struct {
	cc *grpc.ClientConn
}

func NewMerchantServiceClient(cc *grpc.ClientConn) MerchantServiceClient {
	return &merchantServiceClient{cc}
}

func (c *merchantServiceClient) CreateMerchant(ctx context.Context, in *MerchantSchema, opts ...grpc.CallOption) (*MerchantSchema, error) {
	out := new(MerchantSchema)
	err := c.cc.Invoke(ctx, "/merchant.MerchantService/CreateMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*MerchantSchema, error) {
	out := new(MerchantSchema)
	err := c.cc.Invoke(ctx, "/merchant.MerchantService/GetMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) UpdateMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*MerchantSchema, error) {
	out := new(MerchantSchema)
	err := c.cc.Invoke(ctx, "/merchant.MerchantService/UpdateMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) DeleteMerchant(ctx context.Context, in *MerchantQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/merchant.MerchantService/DeleteMerchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchants(ctx context.Context, in *MerchantsQuery, opts ...grpc.CallOption) (*MerchantsResponse, error) {
	out := new(MerchantsResponse)
	err := c.cc.Invoke(ctx, "/merchant.MerchantService/GetMerchants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MerchantServiceServer is the server API for MerchantService service.
type MerchantServiceServer interface {
	// Create a merchant
	CreateMerchant(context.Context, *MerchantSchema) (*MerchantSchema, error)
	// Get a merchant by id
	GetMerchant(context.Context, *MerchantQuery) (*MerchantSchema, error)
	// Update a merchant by id
	UpdateMerchant(context.Context, *MerchantQuery) (*MerchantSchema, error)
	// Delete a merchant by id
	DeleteMerchant(context.Context, *MerchantQuery) (*wrappers.StringValue, error)
	// GetMerchants gets a list of merchants by start and count
	GetMerchants(context.Context, *MerchantsQuery) (*MerchantsResponse, error)
}

func RegisterMerchantServiceServer(s *grpc.Server, srv MerchantServiceServer) {
	s.RegisterService(&_MerchantService_serviceDesc, srv)
}

func _MerchantService_CreateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.MerchantService/CreateMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).CreateMerchant(ctx, req.(*MerchantSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.MerchantService/GetMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchant(ctx, req.(*MerchantQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_UpdateMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).UpdateMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.MerchantService/UpdateMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).UpdateMerchant(ctx, req.(*MerchantQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_DeleteMerchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).DeleteMerchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.MerchantService/DeleteMerchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).DeleteMerchant(ctx, req.(*MerchantQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _MerchantService_GetMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MerchantsQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MerchantServiceServer).GetMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/merchant.MerchantService/GetMerchants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MerchantServiceServer).GetMerchants(ctx, req.(*MerchantsQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _MerchantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "merchant.MerchantService",
	HandlerType: (*MerchantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMerchant",
			Handler:    _MerchantService_CreateMerchant_Handler,
		},
		{
			MethodName: "GetMerchant",
			Handler:    _MerchantService_GetMerchant_Handler,
		},
		{
			MethodName: "UpdateMerchant",
			Handler:    _MerchantService_UpdateMerchant_Handler,
		},
		{
			MethodName: "DeleteMerchant",
			Handler:    _MerchantService_DeleteMerchant_Handler,
		},
		{
			MethodName: "GetMerchants",
			Handler:    _MerchantService_GetMerchants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "merchant/merchant.proto",
}

func init() { proto.RegisterFile("merchant/merchant.proto", fileDescriptor_merchant_fdfe9aaf20316dc3) }

var fileDescriptor_merchant_fdfe9aaf20316dc3 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xdd, 0x4b, 0xf3, 0x30,
	0x14, 0xc6, 0xd7, 0xbe, 0xef, 0xc4, 0x9d, 0x69, 0xc5, 0x20, 0xac, 0x4c, 0x91, 0x91, 0xab, 0x5d,
	0x75, 0x30, 0x87, 0x57, 0x5e, 0xf9, 0x35, 0x44, 0xbc, 0xb0, 0x63, 0xde, 0x67, 0xed, 0xb1, 0x2b,
	0xb4, 0x4d, 0x49, 0x52, 0xc5, 0xff, 0xdc, 0x4b, 0xb1, 0x59, 0xb2, 0xc9, 0x3e, 0x10, 0xef, 0x72,
	0xf2, 0x3c, 0xe7, 0x97, 0x27, 0xc9, 0x81, 0x4e, 0x8e, 0x22, 0x9a, 0xb3, 0x42, 0x0d, 0xcc, 0x22,
	0x28, 0x05, 0x57, 0x9c, 0xec, 0x9b, 0xba, 0x7b, 0x9e, 0x70, 0x9e, 0x64, 0x38, 0xa8, 0xf7, 0x67,
	0xd5, 0xeb, 0xe0, 0x5d, 0xb0, 0xb2, 0x44, 0x21, 0xb5, 0x93, 0x4e, 0xe1, 0xf0, 0x69, 0xe1, 0x7d,
	0xae, 0x50, 0x7c, 0x10, 0x0f, 0xdc, 0x34, 0xf6, 0x9d, 0x9e, 0xd3, 0x6f, 0x86, 0x6e, 0x1a, 0x93,
	0x11, 0x58, 0x98, 0xef, 0xf6, 0x9c, 0x7e, 0x7b, 0xe8, 0x07, 0xf6, 0x34, 0xd3, 0x3a, 0x89, 0xe6,
	0x98, 0xb3, 0xd0, 0x3a, 0xe9, 0x08, 0xbc, 0x9f, 0xda, 0x1a, 0x97, 0xc0, 0xff, 0x82, 0xe5, 0x58,
	0x33, 0x5b, 0x61, 0xbd, 0xa6, 0x57, 0xcb, 0x2e, 0xa9, 0xd3, 0x9c, 0x40, 0x33, 0xe2, 0x55, 0xa1,
	0x16, 0x8d, 0xba, 0xf8, 0xde, 0x95, 0x8a, 0x09, 0x1d, 0xa8, 0x19, 0xea, 0x82, 0x3e, 0xc2, 0xb1,
	0xed, 0x0e, 0x51, 0x96, 0xbc, 0x90, 0x48, 0x2e, 0xa1, 0x65, 0x42, 0x49, 0xdf, 0xe9, 0xfd, 0xdb,
	0x99, 0x7f, 0x69, 0x1d, 0x7e, 0xba, 0x70, 0x64, 0x55, 0x14, 0x6f, 0x69, 0x84, 0xe4, 0x1e, 0xbc,
	0x1b, 0x81, 0x4c, 0xa1, 0x11, 0xc8, 0x56, 0x54, 0x77, 0xab, 0x42, 0x1b, 0xe4, 0x1a, 0xda, 0x63,
	0x54, 0x16, 0xd2, 0x59, 0xb7, 0xd6, 0x97, 0xdf, 0xc9, 0xb8, 0x03, 0x6f, 0x5a, 0xc6, 0xab, 0x59,
	0xfe, 0x84, 0x79, 0x00, 0xef, 0x16, 0x33, 0xfc, 0x0d, 0xe6, 0x2c, 0xd0, 0xa3, 0x14, 0x98, 0x51,
	0x0a, 0x26, 0x4a, 0xa4, 0x45, 0xf2, 0xc2, 0xb2, 0x0a, 0x69, 0x83, 0x8c, 0xe1, 0x60, 0xe5, 0x56,
	0x72, 0xd3, 0xdb, 0xe8, 0x4f, 0xed, 0x9e, 0x6e, 0x50, 0xcc, 0x87, 0xd1, 0xc6, 0x6c, 0xaf, 0x3e,
	0xe0, 0xe2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x2c, 0x31, 0x1a, 0xde, 0x02, 0x00, 0x00,
}
