BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0e394ab31a97

CREATE TABLE product (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT NOT NULL,
    price NUMERIC(30, 16) NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

INSERT INTO alembic_version (version_num) VALUES ('0e394ab31a97');

COMMIT;
