BEGIN;

-- Running upgrade 0e394ab31a97 -> 2946eee19802

CREATE TABLE customer (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE merchant (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT NOT NULL,
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);

CREATE TABLE review (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rating INTEGER NOT NULL,
    review TEXT,
    customer_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    CONSTRAINT pk_review PRIMARY KEY (id),
    CONSTRAINT fk_review_customer_id_customer FOREIGN KEY(customer_id) REFERENCES customer (id),
    CONSTRAINT fk_review_product_id_product FOREIGN KEY(product_id) REFERENCES product (id)
);

ALTER TABLE product ADD COLUMN merchant_id INTEGER NOT NULL;

ALTER TABLE product ADD CONSTRAINT fk_product_merchant_id_merchant FOREIGN KEY(merchant_id) REFERENCES merchant (id);

UPDATE alembic_version SET version_num='2946eee19802' WHERE alembic_version.version_num = '0e394ab31a97';

COMMIT;
