BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 8a5b09852d9c

CREATE TABLE customer (
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    deleted_at TIMESTAMP WITHOUT TIME ZONE, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    first_name TEXT NOT NULL, 
    last_name TEXT NOT NULL, 
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE INDEX ix_customer_deleted_at ON customer (deleted_at);

CREATE TABLE merchant (
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    deleted_at TIMESTAMP WITHOUT TIME ZONE, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    name TEXT NOT NULL, 
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);

CREATE INDEX ix_merchant_deleted_at ON merchant (deleted_at);

CREATE TABLE product (
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    deleted_at TIMESTAMP WITHOUT TIME ZONE, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    name TEXT NOT NULL, 
    price NUMERIC(30, 16) NOT NULL, 
    merchant_id INTEGER NOT NULL, 
    CONSTRAINT pk_product PRIMARY KEY (id), 
    CONSTRAINT fk_product_merchant_id_merchant FOREIGN KEY(merchant_id) REFERENCES merchant (id)
);

CREATE INDEX ix_product_deleted_at ON product (deleted_at);

CREATE TABLE review (
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    deleted_at TIMESTAMP WITHOUT TIME ZONE, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    rating INTEGER NOT NULL, 
    review TEXT, 
    customer_id INTEGER NOT NULL, 
    product_id INTEGER NOT NULL, 
    CONSTRAINT pk_review PRIMARY KEY (id), 
    CONSTRAINT fk_review_customer_id_customer FOREIGN KEY(customer_id) REFERENCES customer (id), 
    CONSTRAINT fk_review_product_id_product FOREIGN KEY(product_id) REFERENCES product (id)
);

CREATE INDEX ix_review_deleted_at ON review (deleted_at);

INSERT INTO alembic_version (version_num) VALUES ('8a5b09852d9c');

COMMIT;
