BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL, 
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 0e394ab31a97

CREATE TABLE product (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    name TEXT NOT NULL, 
    price NUMERIC(30, 16) NOT NULL, 
    CONSTRAINT pk_product PRIMARY KEY (id)
);

INSERT INTO alembic_version (version_num) VALUES ('0e394ab31a97');

-- Running upgrade 0e394ab31a97 -> 2946eee19802

CREATE TABLE customer (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    first_name TEXT NOT NULL, 
    last_name TEXT NOT NULL, 
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE merchant (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    name TEXT NOT NULL, 
    CONSTRAINT pk_merchant PRIMARY KEY (id)
);

CREATE TABLE review (
    committed_timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, 
    rating INTEGER NOT NULL, 
    review TEXT, 
    customer_id INTEGER NOT NULL, 
    product_id INTEGER NOT NULL, 
    CONSTRAINT pk_review PRIMARY KEY (id), 
    CONSTRAINT fk_review_customer_id_customer FOREIGN KEY(customer_id) REFERENCES customer (id), 
    CONSTRAINT fk_review_product_id_product FOREIGN KEY(product_id) REFERENCES product (id)
);

ALTER TABLE product ADD COLUMN merchant_id INTEGER NOT NULL;

ALTER TABLE product ADD CONSTRAINT fk_product_merchant_id_merchant FOREIGN KEY(merchant_id) REFERENCES merchant (id);

UPDATE alembic_version SET version_num='2946eee19802' WHERE alembic_version.version_num = '0e394ab31a97';

-- Running upgrade 2946eee19802 -> f2ea8a1fc7b6

ALTER TABLE customer ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

ALTER TABLE customer ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE customer ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

CREATE INDEX ix_customer_deleted_at ON customer (deleted_at);

ALTER TABLE customer DROP COLUMN committed_timestamp;

ALTER TABLE merchant ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

ALTER TABLE merchant ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE merchant ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

CREATE INDEX ix_merchant_deleted_at ON merchant (deleted_at);

ALTER TABLE merchant DROP COLUMN committed_timestamp;

ALTER TABLE product ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

ALTER TABLE product ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE product ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

CREATE INDEX ix_product_deleted_at ON product (deleted_at);

ALTER TABLE product DROP COLUMN committed_timestamp;

ALTER TABLE review ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

ALTER TABLE review ADD COLUMN deleted_at TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE review ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL;

CREATE INDEX ix_review_deleted_at ON review (deleted_at);

ALTER TABLE review DROP COLUMN committed_timestamp;

UPDATE alembic_version SET version_num='f2ea8a1fc7b6' WHERE alembic_version.version_num = '2946eee19802';

COMMIT;
