// Code generated by protoc-gen-go. DO NOT EDIT.
// source: customer/customer.proto

package customer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import wrappers "github.com/golang/protobuf/ptypes/wrappers"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CustomerQuery
type CustomerQuery struct {
	Id                   int32           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer             *CustomerSchema `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CustomerQuery) Reset()         { *m = CustomerQuery{} }
func (m *CustomerQuery) String() string { return proto.CompactTextString(m) }
func (*CustomerQuery) ProtoMessage()    {}
func (*CustomerQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_fb42d4aaeffc781a, []int{0}
}
func (m *CustomerQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerQuery.Unmarshal(m, b)
}
func (m *CustomerQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerQuery.Marshal(b, m, deterministic)
}
func (dst *CustomerQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerQuery.Merge(dst, src)
}
func (m *CustomerQuery) XXX_Size() int {
	return xxx_messageInfo_CustomerQuery.Size(m)
}
func (m *CustomerQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerQuery proto.InternalMessageInfo

func (m *CustomerQuery) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerQuery) GetCustomer() *CustomerSchema {
	if m != nil {
		return m.Customer
	}
	return nil
}

// The customer interface schema
type CustomerSchema struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomerSchema) Reset()         { *m = CustomerSchema{} }
func (m *CustomerSchema) String() string { return proto.CompactTextString(m) }
func (*CustomerSchema) ProtoMessage()    {}
func (*CustomerSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_fb42d4aaeffc781a, []int{1}
}
func (m *CustomerSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomerSchema.Unmarshal(m, b)
}
func (m *CustomerSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomerSchema.Marshal(b, m, deterministic)
}
func (dst *CustomerSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomerSchema.Merge(dst, src)
}
func (m *CustomerSchema) XXX_Size() int {
	return xxx_messageInfo_CustomerSchema.Size(m)
}
func (m *CustomerSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomerSchema.DiscardUnknown(m)
}

var xxx_messageInfo_CustomerSchema proto.InternalMessageInfo

func (m *CustomerSchema) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomerSchema) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CustomerSchema) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

// CustomersQuery describes a request to get count customers starting at id start
type CustomersQuery struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Start                int32    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomersQuery) Reset()         { *m = CustomersQuery{} }
func (m *CustomersQuery) String() string { return proto.CompactTextString(m) }
func (*CustomersQuery) ProtoMessage()    {}
func (*CustomersQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_fb42d4aaeffc781a, []int{2}
}
func (m *CustomersQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomersQuery.Unmarshal(m, b)
}
func (m *CustomersQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomersQuery.Marshal(b, m, deterministic)
}
func (dst *CustomersQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomersQuery.Merge(dst, src)
}
func (m *CustomersQuery) XXX_Size() int {
	return xxx_messageInfo_CustomersQuery.Size(m)
}
func (m *CustomersQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomersQuery.DiscardUnknown(m)
}

var xxx_messageInfo_CustomersQuery proto.InternalMessageInfo

func (m *CustomersQuery) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *CustomersQuery) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

// CustomersResponse is a list of customers
type CustomersResponse struct {
	Customers            []*CustomerSchema `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CustomersResponse) Reset()         { *m = CustomersResponse{} }
func (m *CustomersResponse) String() string { return proto.CompactTextString(m) }
func (*CustomersResponse) ProtoMessage()    {}
func (*CustomersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_customer_fb42d4aaeffc781a, []int{3}
}
func (m *CustomersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomersResponse.Unmarshal(m, b)
}
func (m *CustomersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomersResponse.Marshal(b, m, deterministic)
}
func (dst *CustomersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomersResponse.Merge(dst, src)
}
func (m *CustomersResponse) XXX_Size() int {
	return xxx_messageInfo_CustomersResponse.Size(m)
}
func (m *CustomersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CustomersResponse proto.InternalMessageInfo

func (m *CustomersResponse) GetCustomers() []*CustomerSchema {
	if m != nil {
		return m.Customers
	}
	return nil
}

func init() {
	proto.RegisterType((*CustomerQuery)(nil), "customer.CustomerQuery")
	proto.RegisterType((*CustomerSchema)(nil), "customer.CustomerSchema")
	proto.RegisterType((*CustomersQuery)(nil), "customer.CustomersQuery")
	proto.RegisterType((*CustomersResponse)(nil), "customer.CustomersResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	// Create a customer
	CreateCustomer(ctx context.Context, in *CustomerSchema, opts ...grpc.CallOption) (*CustomerSchema, error)
	// Get a customer by id
	GetCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*CustomerSchema, error)
	// Update a customer by id
	UpdateCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*CustomerSchema, error)
	// Delete a customer by id
	DeleteCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error)
	// GetCustomers gets a list of customers by start and count
	GetCustomers(ctx context.Context, in *CustomersQuery, opts ...grpc.CallOption) (*CustomersResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CustomerSchema, opts ...grpc.CallOption) (*CustomerSchema, error) {
	out := new(CustomerSchema)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*CustomerSchema, error) {
	out := new(CustomerSchema)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) UpdateCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*CustomerSchema, error) {
	out := new(CustomerSchema)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) DeleteCustomer(ctx context.Context, in *CustomerQuery, opts ...grpc.CallOption) (*wrappers.StringValue, error) {
	out := new(wrappers.StringValue)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomers(ctx context.Context, in *CustomersQuery, opts ...grpc.CallOption) (*CustomersResponse, error) {
	out := new(CustomersResponse)
	err := c.cc.Invoke(ctx, "/customer.CustomerService/GetCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	// Create a customer
	CreateCustomer(context.Context, *CustomerSchema) (*CustomerSchema, error)
	// Get a customer by id
	GetCustomer(context.Context, *CustomerQuery) (*CustomerSchema, error)
	// Update a customer by id
	UpdateCustomer(context.Context, *CustomerQuery) (*CustomerSchema, error)
	// Delete a customer by id
	DeleteCustomer(context.Context, *CustomerQuery) (*wrappers.StringValue, error)
	// GetCustomers gets a list of customers by start and count
	GetCustomers(context.Context, *CustomersQuery) (*CustomersResponse, error)
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CustomerSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomer(ctx, req.(*CustomerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).UpdateCustomer(ctx, req.(*CustomerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).DeleteCustomer(ctx, req.(*CustomerQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomersQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/customer.CustomerService/GetCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomers(ctx, req.(*CustomersQuery))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "customer.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _CustomerService_GetCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _CustomerService_UpdateCustomer_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _CustomerService_DeleteCustomer_Handler,
		},
		{
			MethodName: "GetCustomers",
			Handler:    _CustomerService_GetCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "customer/customer.proto",
}

func init() { proto.RegisterFile("customer/customer.proto", fileDescriptor_customer_fb42d4aaeffc781a) }

var fileDescriptor_customer_fb42d4aaeffc781a = []byte{
	// 342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0x94, 0x7e, 0x69, 0xa6, 0x5f, 0x23, 0x2e, 0x42, 0x43, 0xab, 0x52, 0xf6, 0xd4,
	0x53, 0x0a, 0x55, 0x3c, 0x79, 0xb2, 0x6a, 0x11, 0x41, 0x30, 0xa5, 0x9e, 0x04, 0xd9, 0xa6, 0xd3,
	0x1a, 0x48, 0xb2, 0x61, 0x77, 0xa3, 0xf8, 0x9f, 0x7b, 0x94, 0x6e, 0xba, 0x69, 0xa5, 0x3f, 0x10,
	0x6f, 0x99, 0xf7, 0xde, 0x7e, 0x66, 0x26, 0xbb, 0xd0, 0x0c, 0x73, 0xa9, 0x78, 0x82, 0xa2, 0x67,
	0x3e, 0xfc, 0x4c, 0x70, 0xc5, 0x49, 0xdd, 0xd4, 0xad, 0xb3, 0x39, 0xe7, 0xf3, 0x18, 0x7b, 0x5a,
	0x9f, 0xe4, 0xb3, 0xde, 0x87, 0x60, 0x59, 0x86, 0x42, 0x16, 0x49, 0x3a, 0x86, 0x83, 0xc1, 0x32,
	0xfb, 0x94, 0xa3, 0xf8, 0x24, 0x2e, 0xd8, 0xd1, 0xd4, 0xb3, 0x3a, 0x56, 0xb7, 0x16, 0xd8, 0xd1,
	0x94, 0x5c, 0x40, 0x09, 0xf3, 0xec, 0x8e, 0xd5, 0x6d, 0xf4, 0x3d, 0xbf, 0xec, 0x66, 0x8e, 0x8e,
	0xc2, 0x37, 0x4c, 0x58, 0x50, 0x26, 0xe9, 0x0b, 0xb8, 0x3f, 0xbd, 0x0d, 0xee, 0x29, 0xc0, 0x2c,
	0x12, 0x52, 0xbd, 0xa6, 0x2c, 0x41, 0x4d, 0x76, 0x02, 0x47, 0x2b, 0x8f, 0x2c, 0x41, 0xd2, 0x06,
	0x27, 0x66, 0xc6, 0xad, 0x6a, 0xb7, 0xbe, 0x10, 0x16, 0x26, 0xbd, 0x5a, 0xd1, 0x65, 0x31, 0xf5,
	0x31, 0xd4, 0x42, 0x9e, 0xa7, 0x6a, 0xd9, 0xa0, 0x28, 0x16, 0xaa, 0x54, 0x4c, 0x28, 0x8d, 0xaf,
	0x05, 0x45, 0x41, 0x1f, 0xe0, 0xa8, 0x3c, 0x1d, 0xa0, 0xcc, 0x78, 0x2a, 0x91, 0x5c, 0x82, 0x63,
	0x86, 0x97, 0x9e, 0xd5, 0xa9, 0xee, 0xdd, 0x73, 0x15, 0xed, 0x7f, 0xd9, 0x70, 0x58, 0xba, 0x28,
	0xde, 0xa3, 0x10, 0xc9, 0x1d, 0xb8, 0x03, 0x81, 0x4c, 0xa1, 0x31, 0xc8, 0x4e, 0x54, 0x6b, 0xa7,
	0x43, 0x2b, 0xe4, 0x1a, 0x1a, 0x43, 0x54, 0x25, 0xa4, 0xb9, 0x19, 0xd5, 0xcb, 0xef, 0x65, 0xdc,
	0x82, 0x3b, 0xce, 0xa6, 0xeb, 0xb3, 0xfc, 0x09, 0x73, 0x0f, 0xee, 0x0d, 0xc6, 0xf8, 0x1b, 0xcc,
	0x89, 0x5f, 0x3c, 0x39, 0xdf, 0x3c, 0x39, 0x7f, 0xa4, 0x44, 0x94, 0xce, 0x9f, 0x59, 0x9c, 0x23,
	0xad, 0x90, 0x21, 0xfc, 0x5f, 0xdb, 0x4a, 0x6e, 0xfb, 0x37, 0xc5, 0xa5, 0xb6, 0xda, 0x5b, 0x1c,
	0x73, 0x61, 0xb4, 0x32, 0xf9, 0xa7, 0x1b, 0x9c, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xa4,
	0xdb, 0x1f, 0x06, 0x03, 0x00, 0x00,
}
